[server]
maxUploadSize = 256
enableCORS = true
sslCertFile = 'cert.pem'
sslKeyFile = 'key.pem'
headless = true
port = 40000
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[theme]
base="light"
font="serif"
